extends: "eval_15_mistralsmall_promptV4.yaml"

evaluation:
  eval_run_id: "16_sivas_fixed512_faiss_dense_qwen25_promptV4_eval"

inputs:
  pipeline1_results_path: "data/runs/pipeline1/16_sivas_fixed512_faiss_dense_qwen25_promptV4/results.jsonl"
  rag_outputs:
    - "data/runs/pipeline1/16_sivas_fixed512_faiss_dense_qwen25_promptV4/results.jsonl"
