extends: "eval_14_promptV4.yaml"

evaluation:
  eval_run_id: "15_sivas_fixed512_faiss_dense_qwen25_orchestration_promptV4_eval"

inputs:
  pipeline1_results_path: "data/runs/pipeline1/15_sivas_fixed512_faiss_dense_qwen25_orchestration_promptV4/results.jsonl"
  rag_outputs:
    - "data/runs/pipeline1/15_sivas_fixed512_faiss_dense_qwen25_orchestration_promptV4/results.jsonl"
