extends: "../base_pipeline3.yaml"

pipeline3:
  run_id: "91_sivas_fixed512_faiss_dense_mistralsmall_prompt_v0"

inputs:
  pipeline1_results_path: "data/runs/pipeline1/91_sivas_fixed512_faiss_dense_mistralsmall_prompt_v0/results.jsonl"

ragas:
  enabled: true

llm_judge:
  enabled: true
  max_context_chars: 10000
  metrics:
    correctness: true
    faithfulness: true
    completeness: true
    hallucination: true
    context_relevance: true
