extends: "../base_pipeline3.yaml"

pipeline3:
  run_id: "92_sivas_fixed512_faiss_dense_mistralsmall_prompt_v1"

inputs:
  pipeline1_results_path: "data/runs/pipeline1/92_sivas_fixed512_faiss_dense_mistralsmall_prompt_v1/results.jsonl"
